# Confirm DuckDB version

In [8]:
import duckdb
print(duckdb.__version__)

1.4.0

## Check API connection to GitHub (should print 200 if all is ok)

In [9]:
import requests

headers = {"Authorization": "token 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"}
url = "https://api.github.com/search/repositories?q=stars:>1000&sort=stars&order=desc&per_page=100&page=1"
response = requests.get(url, headers=headers)
print(response.status_code)  # Should print 200 if everything is correct
data = response.json()

200

In [10]:
print(data.keys())
print(data['items'][0]['full_name'])

dict_keys(['total_count', 'incomplete_results', 'items'])
freeCodeCamp/freeCodeCamp

## Save data as a JSON file

In [11]:
import json

# Save the items (list of repositories) to a file
with open('github_repos.json', 'w') as f:
    json.dump(data['items'], f)

## Use DuckDB to read JSON file

In [12]:
import duckdb

# Run SQL directly to read JSON into a DuckDB table (requires 'json' extension)
duckdb.sql("INSTALL 'json'; LOAD 'json';")
duckdb.sql("""
    CREATE OR REPLACE TABLE repos AS
    SELECT * FROM read_json_auto('github_repos.json')
""")
rows = duckdb.sql('SELECT full_name, stargazers_count FROM repos ORDER BY stargazers_count DESC LIMIT 10').fetchall()
print(rows)

[('freeCodeCamp/freeCodeCamp', 427788), ('codecrafters-io/build-your-own-x', 420199), ('sindresorhus/awesome', 400477), ('EbookFoundation/free-programming-books', 368329), ('public-apis/public-apis', 365254), ('kamranahmedse/developer-roadmap', 336591), ('jwasham/coding-interview-university', 327872), ('donnemartin/system-design-primer', 319920), ('996icu/996.ICU', 274334), ('vinta/awesome-python', 260078)]

### List the Most Starred Repositories

In [13]:
results = duckdb.sql("""
    SELECT full_name, stargazers_count
    FROM repos
    ORDER BY stargazers_count DESC
    LIMIT 10
""").fetchall()
for repo in results:
    print(repo)

('freeCodeCamp/freeCodeCamp', 427788)
('codecrafters-io/build-your-own-x', 420199)
('sindresorhus/awesome', 400477)
('EbookFoundation/free-programming-books', 368329)
('public-apis/public-apis', 365254)
('kamranahmedse/developer-roadmap', 336591)
('jwasham/coding-interview-university', 327872)
('donnemartin/system-design-primer', 319920)
('996icu/996.ICU', 274334)
('vinta/awesome-python', 260078)

### Explore Data columns (all columns)

In [14]:
duckdb.sql("DESCRIBE repos").df()

,column_name,column_type,null,key,default,extra
0,id,BIGINT,YES,None,None,None
1,node_id,VARCHAR,YES,None,None,None
2,name,VARCHAR,YES,None,None,None
3,full_name,VARCHAR,YES,None,None,None
4,private,BOOLEAN,YES,None,None,None
...,...,...,...,...,...,...
76,open_issues,BIGINT,YES,None,None,None
77,watchers,BIGINT,YES,None,None,None
78,default_branch,VARCHAR,YES,None,None,None
79,permissions,"STRUCT(""admin"" BOOLEAN, maintain BOOLEAN, push...",YES,None,None,None
80,score,DOUBLE,YES,None,None,None

### List top repositories by programming language:

In [15]:
duckdb.sql("""
    SELECT language, COUNT(*) AS num_repos
    FROM repos
    GROUP BY language
    ORDER BY num_repos DESC
""").df()

            language  num_repos
0             Python         17
1         TypeScript         17
2         JavaScript         14
3               None         13
4                C++          5
5                 Go          5
6               Rust          4
7               Java          4
8   Jupyter Notebook          3
9              Shell          3
10              HTML          3
11                 C          2
12        Dockerfile          2
13          Markdown          2
14        Vim Script          1
15               Vue          1
16               MDX          1
17         Batchfile          1
18                C#          1
19              Dart          1

### Show Top Repositories for a Specific Language

In [26]:
duckdb.sql("""
    SELECT full_name, stargazers_count, language
    FROM repos
    WHERE language = 'JavaScript'
    ORDER BY stargazers_count DESC
    LIMIT 10
""").df()

                         full_name  stargazers_count    language
0                   facebook/react            238952  JavaScript
1   trekhleb/javascript-algorithms            193283  JavaScript
2                airbnb/javascript            147409  JavaScript
3                   vercel/next.js            134500  JavaScript
4        f/awesome-chatgpt-prompts            134133  JavaScript
5  Chalarangelo/30-seconds-of-code            125290  JavaScript
6                      nodejs/node            113258  JavaScript
7            open-webui/open-webui            110134  JavaScript
8                  mrdoob/three.js            108597  JavaScript
9                      axios/axios            107629  JavaScript